name: "dbgit"
description: "A GitHub action that interacts with a database and GitHub"
inputs:
  deploy_schema:
    description: "The schema to deploy"
    required: true
  deploy_schema_password:
    description: "The password for the schema"
    required: true
  action:
    description: "The action to perform"
    required: true
  genpass:
    description: "Password for generator user"
    required: true
  output_directory:
    description: "Artifact output directory"
    required: true
  github_token:
    description: "GitHub token"
    required: true
  pr_number:
    description: "Pull request number"
    required: true
  repo_name:
    description: "Repository name"
    required: true




runs:
  using: "docker"
  image: "pioro/syncer:latest"
  env:
    GITHUB_TOKEN          : ${{ inputs.github_token }}
    PR_NUMBER             : ${{ inputs.pr_number }}
    REPO_NAME             : ${{ inputs.repo_name }}
    DEPLOY_SCHEMA         : ${{ inputs.deploy_schema }}
    DEPLOY_SCHEMA_PASSWORD: ${{ inputs.deploy_schema_password }}
    ACTION                : ${{ inputs.action }}
    GENPASS               : ${{ inputs.genpass }}
    OUTPUT_DIRECTORY      : ${{ inputs.output_directory }}
  args:
    - --outputroot ${{ inputs.output_directory }}
    - --sysdba
    - --repopath /github/workspace
    - --host docker
    - --port 1521
    - --service target
    - --username sys 







                       