CREATE TABLE "PIORO"."TESTTAB2" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;