CREATE TABLE "PIORO"."TESTTAB1" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(100), 
	"LAST_NAME" VARCHAR2(301), 
	"LAST_NAME2" VARCHAR2(301), 
	"LAST_NAME3" VARCHAR2(301), 
	"LAST_NAME4" VARCHAR2(301)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;