
name: Run on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main   # or your target branch(es)

jobs:
  on-pr-merge:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
           fetch-depth: 0

      - name: Print PR info
        run: |
          echo "Pull request #${{ github.event.pull_request.number }} was merged into ${{ github.event.pull_request.base.ref }}"

   #   - name: test
   #     run: gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[]'
   #     env:
   #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Changed Files Exporter
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        id: changed-files

           
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

 #     - name: Pythonie
 #       env:
 #          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
 #          PR_NUMBER    : ${{ github.event.pull_request.number }}
 #          REPO_NAME    : ${{ github.repository }}
 #       run: |
 #          cd /home/docker/check
 #          python3 check.py


      - name: Run tests in container
        run: |
          ls -l $RUNNER_TEMP
          cd $GITHUB_WORKSPACE
          ls -l 
          docker run --rm --name generator -e ACTION=config \
          -v /home/pioro/workdir:/workdir  \
          -v /home/pioro/output:/output   \
          -v /home/pioro/workdir:/config   \
          -v $GITHUB_WORKSPACE/:/dbcode \
          pioro/syncer:latest \
          --repopath /dbcode \
          --outputroot /output \
          --host docker \
          --port 1521 \
          --service test19 \
          --username ${{ vars.GEN_USER }} \
          --sysdba \
          --gitea_url http://a.a.a.a 

      - name: Run tests in container 2nd
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER    : ${{ github.event.pull_request.number }}
          REPO_NAME    : ${{ github.repository }}
        run: |
            docker run -e GITEA_API="aa" \
                       -e GITHUB_TOKEN=$GITHUB_TOKEN \
                       -e PR_NUMBER=$PR_NUMBER \
                       -e REPO_NAME=$REPO_NAME \
                       -e DEPLOY_SCHEMA=${{ vars.UTILITIES_USER }}  \
                       -e DEPLOY_SCHEMA_PASSWORD=${{ secrets.UTILITIES_PASS }} \
                       -e ACTION=generateall \
                       -e GENPASS=${{ secrets.GENPASS }} \
                       -v /home/pioro/.ssh/id_rsa_robot:/ssh/id_rsa.docker \
                       -v /home/pioro/.ssh/config:/ssh/config \
                       -v /home/pioro/workdir:/workdir  \
                       -v /home/pioro/output/:/output   \
                       -v /home/pioro/workdir:/config   \
                       -v $GITHUB_WORKSPACE:/dbcode \
                       pioro/syncer:latest

      - name: Run my action
        uses: ./.github/actions/my-action/
        with:
          username: "Alice"
          token: ${{ secrets.GITHUB_TOKEN }}
          marcin: "dupa"

      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY


